server: 
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://dpg-d4dqacshg0os738e8420-a.oregon-postgres.render.com/aula15
        username: aula15_user
        password: X1mhAG6Ano9DAmjRDfZBRxj1iyPmmXk2
        driver-class-name: org.postgresql.Driver
        initialize: true
        
    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres